"""Generate only Nunito text masks; no vendor artwork or external downloads."""
from pathlib import Path
import hashlib
import json
import re
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "firmware/main/assets/ui_assets.h"
# Stable identifiers, English, Turkish, size, weight.
LABELS = [
    ("Claude", "Claude", "Claude", 21, 800), ("Codex", "Codex", "Codex", 21, 800),
    ("Hello", "Hello there.", "Merhaba.", 21, 800),
    ("Talk", "Listening...", "Konuş...", 21, 800),
    ("Connect", "Let's connect.", "Bağlanalım.", 18, 800),
    ("Wait", "Open voice", "Ses modunu aç", 16, 800),
    ("Done", "All done.", "Tamam.", 21, 800),
    ("Timeout", "Take a breath.", "Bir nefes.", 18, 800),
    ("Error", "Audio stopped.", "Ses kesildi.", 17, 800),
    ("HoldHint", "Hold to speak.", "Basılı tut, konuş.", 12, 600),
    ("ConnectHint", "Connect USB to host.", "USB ile bağlan.", 12, 600),
    ("WaitHint", "Start the host app.", "Uygulamayı başlat.", 12, 600),
    ("OpenHint", "Mic streaming", "Mikrofon açık", 12, 600),
    ("ClosedHint", "Mic muted", "Mikrofon sessiz", 12, 600),
    ("TimeoutHint", "Release and retry.", "Tuşu bırakıp dene.", 12, 600),
    ("ErrorHint", "Reconnect USB.", "USB'yi yeniden tak.", 12, 600),
    ("Draft", "DICTATION", "YAZIYA DÖK", 10, 800),
    ("Voice", "VOICE CHAT", "SESLİ SOHBET", 10, 800),
    ("Usb", "USB", "USB", 10, 800), ("NoUsb", "NO USB", "USB YOK", 10, 800),
    ("Hold", "Hold to talk", "Basılı tut", 11, 700),
    ("Release", "Release: end", "Bırak: bitir", 11, 700),
    ("Retry", "Release button", "Tuşu bırak", 11, 700),
    ("NextClaude", "Claude", "Claude", 11, 700),
    ("NextCodex", "Codex", "Codex", 11, 700),
    ("Reconnect", "Reconnect", "Yeniden bağla", 11, 700),
]


def font(size, weight):
    # Do not let optional RAQM availability change kerning between OS wheels.
    result = ImageFont.truetype(str(ROOT / "assets/fonts/Nunito.ttf"), size,
                                layout_engine=ImageFont.Layout.BASIC)
    result.set_variation_by_axes([weight])
    return result


def values(name, data):
    rows = [f"inline constexpr uint8_t {name}[] = {{"]
    rows += ["    " + ",".join(str(v) for v in data[i:i+24]) + "," for i in range(0, len(data), 24)]
    return "\n".join(rows + ["};"])


def main():
    metrics = []
    parts = ["// Generated by tools/build_assets.py; do not hand-edit.",
             "// Nunito text masks: SIL OFL 1.1, assets/fonts/OFL.txt.",
             "#pragma once", "#include <cstdint>",
             "#ifdef ESP_PLATFORM", '#include "sdkconfig.h"', "#endif",
             "namespace voice_ui::assets {",
             "struct Mask { int width, height; const uint8_t* data; };",
             "enum class Label { " + ", ".join(row[0] for row in LABELS) + " };",
             "#if (defined(CONFIG_STICKS3_UI_TURKISH) && CONFIG_STICKS3_UI_TURKISH) || (defined(STICKS3_UI_TURKISH) && STICKS3_UI_TURKISH)"]
    for language in (2, 1):
        masks = []
        for row in LABELS:
            name, size, weight = row[0], row[3], row[4]
            text = row[language]
            f = font(size*3, weight)
            bbox = f.getbbox(text)
            w, h = (bbox[2]-bbox[0]+2)//3, (bbox[3]-bbox[1]+2)//3
            if name in {"Hello", "Talk", "Connect", "Wait", "Done", "Timeout", "Error"}:
                max_width, max_height = 127, 24
            elif name.endswith("Hint"):
                max_width, max_height = 126, 17
            elif name in {"Draft", "Voice"}:
                max_width, max_height = 111, 12
            elif name in {"Hold", "Release", "Retry", "Reconnect"}:
                max_width, max_height = 116, 12
            elif name == "Usb":
                max_width, max_height = 30, 13
            elif name == "NoUsb":
                max_width, max_height = 55, 13
            else:
                max_width, max_height = 130, 23
            assert w <= max_width and h <= max_height, (name, w, h)
            metrics.append(dict(locale="tr" if language == 2 else "en", id=name,
                                text=text, width=w, height=h,
                                max_width=max_width, max_height=max_height))
            image = Image.new("L", (w*3, h*3))
            ImageDraw.Draw(image).text((-bbox[0], -bbox[1]), text, font=f, fill=255)
            image = image.resize((w, h), Image.Resampling.LANCZOS)
            parts.append(values("label_"+name, image.tobytes()))
            masks.append(f"{{{w},{h},label_{name}}}")
        parts.append("inline constexpr Mask labels[] = {" + ",".join(masks) + "};")
        parts.append("#else" if language == 2 else "#endif")
    digits = bytearray()
    for char in "0123456789:":
        image = Image.new("L", (21, 36))
        ImageDraw.Draw(image).text((0, -3), char, font=font(33, 800), fill=255)
        digits.extend(image.resize((7, 12), Image.Resampling.LANCZOS).tobytes())
    parts.extend([values("digits", digits), "}"])
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(parts)+"\n", encoding="utf-8")
    # Check actual source palette text pairs, including disabled footer labels.
    source = (ROOT / "firmware/main/voice_ui.cpp").read_text()
    contrast = []
    def luminance(color):
        values = [(color >> shift & 255)/255 for shift in (16,8,0)]
        linear = [x/12.92 if x <= .04045 else ((x+.055)/1.055)**2.4 for x in values]
        return sum(x*w for x,w in zip(linear, (.2126,.7152,.0722)))
    for theme in ("Warm", "Cool"):
        match = re.search(r"constexpr Palette " + theme + r"\{([^}]+)\}", source)
        palette = dict(zip(("bg","ink","muted","line","surface","accent","pill","green"),
                           [int(x,16) for x in match.group(1).split(",")]))
        for fg,bg in (("ink","bg"),("muted","bg"),("ink","surface"),
                      ("muted","surface"),("accent","surface"),("accent","pill"),("green","surface")):
            low,high = sorted((luminance(palette[fg]),luminance(palette[bg])))
            ratio = (high+.05)/(low+.05)
            assert ratio >= 4.5, (theme,fg,bg,ratio)
            contrast.append(dict(theme=theme,foreground=fg,background=bg,ratio=round(ratio,3)))
    metrics_path = ROOT / "assets/previews/label-metrics.json"
    metrics_path.parent.mkdir(parents=True,exist_ok=True)
    metrics_path.write_text(json.dumps(dict(labels=metrics,contrast=contrast),ensure_ascii=False,indent=2)+"\n")
    print("ui_assets.h SHA256:", hashlib.sha256(OUT.read_bytes()).hexdigest())


if __name__ == "__main__":
    main()
